### ISSUE TITLE
Clarify concepts in heemod

### ISSUE THREAD

**Issue by pierucci** [pierucci/heemod#105]
There is some confusion between:

  * Base model,
  * Least effective model,
  * Less effective model (in incremental comparisons).

This will create problems (e.g. in sensitivity analysis) especially in situations with more than 2 models.

**Comment by pierucci** [comment]
**What is a model**

Concepts in `heemod` are not clear. The word *model* can refer to a strategy modeled by a single Markov process (output of `define_model()`), to the result of the simulation of this process for a given number of cycles (output of `run_models()` with a single model), or to the comparison of multiple strategies (output of `run_models()` with multiple models).

Only one of these concept should be called a *model*. We should decide what is a model, and how to call the rest.

I think the output of `define_model()` could be called a *model*. `run_models()` could be renamed `run_simulation()`. The result would be called a *simulation*. So a *simulation* is one or more *model* run for a given number of cycles. A *simulation* with more than one *model* would also contain a *comparison* of the *models*.

**What is the base model**

The *base model* is the model located at the origin of the CE plane. By default the *base model* is the least effective *model*, unless specified otherwise by the user. Relative cost and effect are calculated relatively to this model.

The *comparison model* of a given *model* is the *model* having the following properties:

  * The first less effective model.
  * _And_ on the efficiency frontier.

Every model is compared to its *comparison model* to calculate incremental cost and effect (and of course ICER). The least effective model does not have a comparison model.

**What results are presented**

When a *simulation* of multiples *models* is run, the results presented are:

  * The absolute values of each models, and among them the absolute cost and effect. This would be the only result presented when a *simulation* is run with only one *model*.
  * The relative values of each model, compared to the *base model*.
  * The incremental cost and effect of each model, each compared to its *comparison model*.

**Comment by pierucci** [comment]
**Suggestion for renaming functions in `heemod`**

Why rename functions? Because it is still time, we are not at version 1.0 yet. The more we wait, the more users will depend on the package and changes will break their workflow. It should go smoothly if we do:

  1. Create the new functions and keep the old ones (mapping to the new ones) with a warning.
  2. A few month later delete the old functions. User will have the time to adapt to the changes.

Simpler functions names:

```r
# define_matrix() becomes transitions()
# (or tm()?)
mat <- transitions(
  .5, .5,
  .1, .9
)

# define_parameters() becomes parameters()
par <- parameters(
  a = 1,
  b = 2
)

# define_state() becomes state()
s1 <- state(
  cost = 123,
  effect = 321
)
s2 <- state(
  cost = 456,
  effect = 765
)

# define_model() becomes model()
m1 <- model(
  transitions = mat,
  s1 = s1,
  s2 = s2
)

# run_models() becomes simulate()
simulate(
  m1,
  parameters = par,
  cycles = 10,
  cost = cost,
  effect = effect
)
```

**Comment by pierucci** [comment]
...continued:

```r
# define_sensitivity() becomes dsa()
se <- dsa(
  a, 0, 2,
  b, 1.5, 2.5
)

# and output from dsa() is actually a function...
se(res) # replaces run_sensitivity(res, se)

# same thing with define_resample() -> psa()
resamp <- psa(
  a ~ norm(1, .5),
  b ~ logitnorm(2, .3)
)

# correlation() replaces define_correlation()
cs <- correlation(
  a, b, .3
)

# and the output from psa() is also a function
psa(res, cs) # replaces run_probabilistic(res, cs)
```

**Comment by ZdenekKabat** [comment]
Hi Antoine,

I have mixed opinions on this:

- I agree that _model_ is by definition a possible strategies but at the same time I have no objections against calling the run itself as _run model_. For me a _simulation_ would be the PSA when multiple scenarios are executed. On the other hand, I would not mind renaming _model_ as _strategy_, for instance.

- Function renaming: even though the new function names are shorter, I find "define_" set of functions more consistent and less generic. Especially function names as _model_, _simulation_ and _correlation_ sound very general and I myself am trying to avoid this type of naming convention.

So in general, I find the current state pretty good and would tend to to less changes rather than more.

**Comment by vojtech-filipec** [comment]
Hello Antoine, 
My suggestions for the concepts:

### ad Model:
- Considering the general meaning of this term, I feel **model** as a simplified specification of the real process; for me it is synonymous to *description of the process*. In your words, it would be a strategy to modeled by the Markov process. The models we use are parametrised and based on the set of parameters you use for one run, you have various classes of a model (base model, less effective model, least effective model, etc.) I would call these classes **strategies** [as in "Strategy A comprises the standard of care, while Strategy B relates to the new drug."]
- Running a model with a set of parameters (i.e. with one strategy) for a given number of cycles produces results. I would call them **model results** or *model outcomes* or *model runs*, although for myself, the later term evokes the process of running [as in "the model run took 40 minutes"]. Based on the strategy, we would speak about e.g. *base-model results*, or *least-effective-model results*.
- Comparing *model results* among several sets of parameters (i.e. strategies), we would get **comparison results** or more briefly *comparisons*. 
- My understanding of **simulation** is the one that @ZdenekKabat described: the PSA results, i.e. something comprising a stochastic component. In this sense, all previous results are deterministic as they depend solely on the set of inputs and not on generated values. 
- (I have no opinion how to call the results of the PSA - shall it be *boundary results*?)

### ad Names of the functions: 
- Completely agree with keeping the "define_" prefix and make the function names rather long and descriptive than short and short and generic. Whenever I explore a new package and see a list of functions, I am happy if they are visually grouped by prefixes like "define_", "util_", "calc_" (calculate), "plot_", "aux_" (auxiliary, internal utility functions).

**Comment by MichaelSvm** [comment]
Hi Antoine.
I similar coments as Zdenek Kabat above. In short:
- apart from define_model I find your naming fine since the names are clear and difficult to missunderstand. Also: with these names there is no risk that there will be a mixup with generic names in R. 
- define_model is a bit confusing though. define_strategy would be better.

**Comment by KZARCA** [comment]
For function naming, I would suggest, following the previous comments:

- `define_strategy` instead of `define_model()`
- `run_model()` instead of `run_models()`
- `define_transition` instead of `define_matrix()`


To be more consistent, I would also suggest to use:
 - `define_dsa()` instead of `define_sensitivity()`
 - `define_psa()` instead of `define_resample()`
 - `run_dsa()` instead of `run_sensitivity()`
 - `run_psa()` instead of `run_probabilistic()`

**Comment by ZdenekKabat** [comment]
@KZARCA This is actually very good, I like it!
