### ISSUE TITLE
Package build fails if WHO API is down

### ISSUE THREAD

**Issue by ZdenekKabat** [pierucci/heemod#118]
The example in heterogeneity.Rmd needs get_who_mr() function to generate results. If WHO API is down, the build fails with an error "No data returned." It takes a while to find reason for the failure so I have two suggestions:

- Generate more informative error message if it is not possible to get data from WHO API
- Get some mortality table offline to the package so that the API downtime does not affect the package development

**Comment by pierucci** [comment]
Yeah this API problem is starting to be an issue. I also got an email from CRAN yesterday asking me about this.

The error message could indeed be more specific, I'll do that in the rgho package.

For the API problem we can do the following things:

  * _Do nothing and hope WHO fixes the issue._ This approach is only OK if 1)GHO uptime is great, 2)WHO is reactive to fix issues, and 3)we can communicate with WHO IT in case there is a problem. Given that 1)this is not the first time their server fails, 2) the server has been down for more than 48h now and 3)WHO GHO team never answered any of my emails in the last months, I don't think this is a great idea.
  * _Modify the vignettes and the tests so they do not fail if the GHO server is down._ I don't like this idea because it just hides the problem. The fact is that when the server is down the functionnality is broken for the users, so we need to find a solution because it makes the package unusable.
  * _Cache GHO mortality data._ We can do that using package supplementary data that we would download from the GHO server, or by running a mirror server. While this would solve the problem, this raises questions about how to keep the data up to date, and also about engaging our responsability. And also legal questions about use of their data maybe?

So I think we're going toward caching data, but we need the think more about the consequences.

For the current episode of failing tests I still hope WHO will do something about it today...

**Comment by pierucci** [comment]
Seems to be fixed now...

https://travis-ci.org/pierucci/heemod

**Comment by pierucci** [comment]
http://r-pkgs.had.co.nz/data.html#data
