### ISSUE TITLE
Print warnings/errors in DSA

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#160]
- When the range does not include the value
- All global parameters must have a name

**Comment by pierucci** [comment]
This is not possible when DSA is defined. Indeed because parameters and DSA specification are unevaluated expressions, they do not have a value yet, and thus cannot be compared.

I see 2 solutions:

  1. Throw an error at DSA evaluation by checking the `eval_parameter` object against the reference object. This is not trivial because it implies re-writing a lot of the internal code in `eval_strategy_newdata` to include those additional checks, all that for a dubious benefit.
  2. Do nothing, the user will see that the results are wrong (actually the results are not *wrong*, they just do not make sense. This is an important difference because a user might get fooled by wrong results, on the other hand an user who does not notice results that do not make sense is the only one to blame).

I vote strongly for number 2.
