### ISSUE TITLE
[SHINY] Modules with empty names are created

### ISSUE THREAD

**Issue by pierucci** [pierucci/heemod#187]
Modules with empty names are created when the "+" button is pressed but the "OK" button is not pressed.

**Comment by KZARCA** [comment]
In order to simplify the code, I gave the same id for the "edit" row and for the normal row: for instance equationName0 for the first module.
Once you click on the module name, it creates a textInput to type the name. The default name at creation is "", it cannot be NULL, so I think we cannot avoid the use of a filter.
