### ISSUE TITLE
add km_until and cycle_length to run_model function?

### ISSUE THREAD

**Issue by MattWiener** [pierucci/heemod#233]
I'm working on the use of part_surv models for transitions.   One thing that needs to be specified to use a part_surv model is the time at which to stop using the Kaplan-Meier estimate and move to using probabilities based on the fit model.   That's something that could be changed from run to run, and so belongs more in the options object, along with things like the initial condition and the method, rather than in the model definition itself.   If that's true, it should probably be changed in run_model, where the options are incorporated, rather than during model definition.   Similarly for cycle_length.

Does that make sense to you?  If so, I'll proceed.

**Comment by pierucci** [comment]
To put your question in perspective I'll try to explain here how I see the evolution of the package: to me the transition matrix method from `define_matrix()` or the part surv method from `define_part_surv()` are just 2 different "engines" that `heemod` can use to compute transitions. That means new engines could be added in the future (I'm mostly thinking about dynamic models).

To integrate these changes easily I'd rather avoid to "hard-code" engine-specific options in functions like `run_model()`. What do you think about an argument to `run_model()` called something like `transition_control`. This argument would take a list of control parameters that could vary according to the engine used (similar to the `control` argument from `lme4::glmer()` where the options can vary with the optimisation algorithm).

**Comment by MattWiener** [comment]
Ah - I was thinking about something like this too, but I didn't think you would like the idea.    One place to put these options would be in the "options" object / file, along with methods and init and so on.   Then we could actually simplify run_model to take the options object instead of the individual pieces.  Or do you prefer that the transition probability options be in a different chunk?

**Comment by MattWiener** [comment]
I've made a start at this in the branch "matt_20170214".   It so far only allows us to change km_limit and cycle_length, but it would, I think, easily adapt to covering more general approaches to switching curves.

Jordan - if you have any references on the kind of curve switching you're doing, I'd love to take a look.

**Comment by jrdnmdhl** [comment]
Apologies for the length of my comment below.  I spend a lot of time on survival projections in partitioned survival models, so it is a bit of a passion of mine.

I don't think I have any great documents to references, but here are some of the operations that I think are useful (bolded most important):
**-Project: take a set of _n_ survival curves, and a set of _n-1_ cutpoints, and return the composite distribution.**
-Pool: take a set of _n_ survival curves, and a set of _n_ weights, and return the composite distribution.
-Accelerate: take a survival curve, and an acceleration factor, and return the adjusted distribution.
**-Apply hazard ratio: take a survival curve, and a hazard ratio, and return the adjusted distribution.**
-Max hazards: Take a set of survival distribution and return a survival distribution reflecting the distribution with the highest failure probability in each cycle
-Additive hazards: Take a set of survival distribution and return a survival distribution reflecting each on as an independent source of risk.

Implementation might be done by treating the result of each operation as its own class, and defining for each such class an implementation of `get_probs_from_surv`.  That would ensure that all such survival distribution objects can be treated generically and that such operations could therefore be piped together.  Example:

```r
# Take a kaplan-meier distribution, apply a hazard ratio of 0.5, project from cycle 20-50 using 
#another parametric distribution, from cycle 50+ using a third distribution, and apply general
#population mortality on top

my_dist = hr(km_dist1, 0.5) %>%
  project(parametric_dist, cut=20) %>%
  project(registry_dist, cut=50)  %>%
  add_hazards(life_table_dist)
```

This should not be very hard to do.  Would be happy to put together a pull request if doing so would be helpful.

**Comment by MattWiener** [comment]
that sounds great!   One question:   as you stitch the various curves together, what do you do if they don't match up, as presumably they often don't?    Do we just accept that?  Or do you do some kind of smoothing to make them come together?    Just accepting it is probably more rigorous, but you could potentially have some people in your model come back from the dead if the survival curve jumps up at one of your cutpoints, which is awkward.

**Comment by jrdnmdhl** [comment]
The stitching would be done based on the per-cycle failure probabilities, rather than the survival probabilities themselves.  This way, it always picks up where the previous distribution leaves off.

**Comment by MattWiener** [comment]
I can't speak for Antoine, but I would be thrilled if you submitted that code.

**Comment by jrdnmdhl** [comment]
Glad to help!  Will start work on that (unless Antoine objects) once I finish this next PR for flexsurv.

**Comment by jrdnmdhl** [comment]
BTW, would be very helpful to know which branch you'd like this on.  Development seems to be moving on a few parallel tracks, would like to make sure I target the right one.

**Comment by pierucci** [comment]
Great idea. I particularly like how it elegantly solves #201.

I am under the impression that the implementation will be [interesting](http://www.catb.org/jargon/html/I/interesting.html). I'm not sure I understand everything, so please correct me where I'm wrong:

@jrdnmdhl mentioned giving the result of each operation its own class, it implies that each operation needs to have a method for each of these classes if one wants to chain operations? If that's the case the complexity of the implementation increases with the square of the number of operations (a class per operation * a method per operation). We should assume we'll think of new operations in the future.

Furthermore in functions taking 2 survival curves such as `project()` the dispatch should depend on the class of the 2 curves. That implies using S4.

Question 1: do you think it would be possible to have functions that work on *evaluated* survival transition probabilities (i.e. vectors of probabilities)? Everything would be much easier, because whatever the survival source is all probabilities can be treated in the same way, avoiding all the multiple class headache. This would work like that (it doesn't look nice right now because using `get_probs_from_surv()` and referencing `markov_cycle` or `state_time` is too unwieldy):

```r
my_dist = get_probs_from_surv(km_dist1, markov_cycle) %>%
  hr(0.5) %>%
  project(get_probs_from_surv(get_probs_from_surv(parametric_dist, cut=20) %>%
  project(get_probs_from_surv(registry_dist, markov_cycle), cut=50)  %>%
  add_hazards(get_probs_from_surv(life_table_dist, markov_cycle))
```

Question 2: from what you describe your functions (e.g. `project()`) are binary, they do not take an arbitrary number of curves. I think binary functions are probably better anyway for chaining. A function taking *n* survival curves would look like that:

```r
project(x, y, z, at = c(3, 8))
```

With binary functions you have to use chains, but IMHO it looks better:

```r
x %>% project(y, 3) %>% project(z, 8)
```

[About branches.](https://github.com/pierucci/heemod/wiki/Pull-requests)

**Comment by jrdnmdhl** [comment]
Hi Antoine,

Thanks for your comments and questions.

To clarify, I don't think we need to we _need_ these operations to be generics.  They only need to return objects which have a generic for  `get_probs_from_surv`. The project function doesn't need to do anything with the distributions it is passed other than arrange them into a nice list structure with a class attribute.  As such, it can be the exact same method regardless of the classes of the objects it is passed.

You only need to interact with the child distributions once `get_probs_from_surv` is called, and then you can take advantage of the fact that every thing **is** a survival distribution' already implements `get_probs_from_surv`.  So the whole thing can be done with one generic per operation.

Q1: That would work for some operations, but not others.  In particular, you need the full distribution to accelerate because your mapping one set of times to another rather than mapping one set of probabilities to another.  In any case, I think the approach I described above is probably clean enough to avoid the need for working on the evaluated probabilities.

Q2:  Yes, I think the binary approach looks nicer, though I don't think we need to choose.  Both would work fine using `...` and then the user can decide depending on circumstance.  Not everybody likes to pipe, and those who don't would rather pass them all in in one go.

Thanks,
Jordan

**Comment by jrdnmdhl** [comment]
I have put together a gist which should provide a more clear sense of how I plan on implementing this.  Would appreciated any feedback.

https://gist.github.com/jrdnmdhl/fc7c683c58f89f827345ce4ef7905d1c

**Comment by pierucci** [comment]
I had a look at you gist, I think I understand way better now. Thanks.

I like the way you plan to do it. The recursive structure of the "survival operation object" is quite smart and elegant. It would be possible to add new operations easily and cleanly. I'd be very happy if you did a pull request with that!

I'm curious how you would integrate an `interpolate()` function in that framework?

**Comment by jrdnmdhl** [comment]
That depends on the kind of interpolation you mean.  Do you have a particular use case in mind?

**Comment by pierucci** [comment]
I was thinking of linear interpolation between projected hazard functions. But as you said it's not that much of an issue because we work on per-cycle probabilities,

**Comment by jrdnmdhl** [comment]
While the project method will ensure that the survival probabilities are continuous, it won’t ensure that the hazard rates are.  As such, I think there will still be room for smoothing projection between two curves.  For example, if you wanted to transition from the hazards of one distribution to another 
over the interval of t=10 to t=15, you might do:
```r
surv_1 %>% project_smooth(surv2, from=10, to=15, method="linear")
```

**Comment by pierucci** [comment]
I see, thanks for the explanation.

**Comment by pierucci** [comment]
Closing the issue because most of the features are implemented. If hasard smoothing is needed a separate issue will be created.
