### ISSUE TITLE
improve vignette

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#27]
non homogeneous 
==============
  1. explain `age  <- floor(age/10-.5)*10+5`
  2. replace `merge(data.frame(age = age, sex = sex), death_prob)$mr` by `death_prob[death_prob$age == age & death_prob$sex == sex, "mr"]` (more intuitive)
  3. standardRR should be renamed
  4. define markov_cycle variable
  5. should set the variables standard treatment costs 394 and NP1 costs 579 somewhere in the text and in the code (not at the end)

homogeneous
============

**Comment by pierucci** [comment]
Points 1 & 2 will be addressed by #28.

Not sure about point 3, since this is the name given to the variable in the example textbook.

What do you mean about point 4? The variable should be better explained in the text?

For point 5 these cost are not part of the model, so it may be difficult to add them to the code, except if the possibility to add "entry cost" to the model is given (cost for every individual given at the start of the model). Created an issue #31.

**Comment by KZARCA** [comment]
Ok for point 3, but what does standardRR mean? Maybe add a comment to the code?
Yes, the example is not reproductible as markov_cycle has not been defined in the code before the first apparition.

**Comment by pierucci** [comment]
Do you actually get an error? Because `markov_cycle` is a variable specially created and shouldn't be defined.

If this isn't clear in the vignette then I should explain it better.
