### ISSUE TITLE
the mr_function(age, sex) should be a core function for non homogeneous markov

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#28]

**Comment by pierucci** [comment]
It's true that computing mortality rates will be a common occurrence in Markov models. But implementing this function in a straightforward way will be non-trivial because the way age is coded in the model and the mortality table will probably differ most of the time. So we need a method to make this correspondance easy:

  1. The user can transform the age variable before passing it to the function. Hardest for the user, easiest for us.
  2. Provide a commodity function to transform age easily. Something like `cut()`.
  3. The function tries to guess the best solution. Difficult to program, time consuming, and can generate hard to debug errors for the user. Dangerous.

Solution 2. appears to be an interesting compromise.

Proposed name: `get_mr(age, sex, life_table)`.

**Comment by KZARCA** [comment]
Solution 2 seems perfect to me
