### ISSUE TITLE
improve summary function

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#29]
- Compute ICER

**Comment by pierucci** [comment]
To compute ICER we need to know which state values correspond to cost and effectiveness/utility. Since state value names are provided by the user there is no way to have default values.

Arguments should be added to `summary()`: `cost` and `endpoint` to provide the variable used to compute ICER.

Furthermore, more than 2 models can be given to `run_model`. In that case which model is the reference and which comparisons should be computed is undetermined. This could be solved using an ICER matrix. Example for 3 models A, B and C:

|   | A | B | C |
-----------------
| A | - | ICER A vs B | ICER A vs C |
| B | ICER B vs A | - |ICER B vs C |
|C | ICER C vs A | ICER C vs B | - |

**Comment by KZARCA** [comment]
You should read Drummond ;)
You don't have to compare each option with each other; what you should do is instead order the strategies by cost, and compute the ICER versus the strategy immediately less costly. 
Go find me in order to give a brief presentation of what I mean

**Comment by pierucci** [comment]
`summary()` now computes ICER sequencially. The efficiency frontier is also computed. The output could be more polished, so I won't close this issue right now.
