### ISSUE TITLE
default for run_model()

### ISSUE THREAD

**Issue by KZARCA** [pierucci/heemod#45]
Usually, we measure number of people being in a state.
So we should not start with only one person.

**Comment by pierucci** [comment]
People indeed do that. But for anything other than microsimulation it is actually meaningless because Markov models are perfectly deterministic. Following 10 or 10000 people is actually exactly the same thing.

Having 1 person in the model is equivalent to presenting results as probabilities rather than counts. I think it is clearer. Furthermore if the default is not 1 then what should it be? 10, 1000? 42?

On the other hand there's a problem when a model is computed on more than 1 person: model differences are not presented per person. I propose a fix for that #54.

**Comment by KZARCA** [comment]
Yeah I know that's the same. But I think starting with 1000 persons should be more pedagogical.
