### ISSUE TITLE
get_state_names does not seem to work on state lists

### ISSUE THREAD

**Issue by MattWiener** [pierucci/heemod#83]
I'm having an issue with method dispatch in heemod. I've searched R_help and stackoverflow without success.   (I saw one post where a function was being masked, but I can't find another package with get_state_names.)  Any help appreciated.

sampleTM <- f.transition.prob.matrix.from.tabular(trans_probs = "sampleTM.csv", state_names = c("A", "B", "C"))
heemod:::get_state_names(sampleTM)
Error in UseMethod("get_state_names") : 
  no applicable method for 'get_state_names' applied to an object of class "c('uneval_matrix', 'lazy_dots')"

I would have expected this to call heemod:::get_state_names.uneval.matrix, which does work on the function when called.

**Comment by pierucci** [comment]
First a question: you seem to describe a problem with transition matrix objects, and not state lists. I do not understand how this is related to the title of this issue?


I think that methods (such as `get_state_names.uneval.matrix()`) are not available from the base environment because the generic `get_state_names()` is not exported from the package namespace.

To get state names from a transition matrix you really need to use `heemod:::get_state_names.uneval.matrix()`. But using this function is somewhat dangerous because it is not exported for a reason: it is supposed to be for internal use only and may be changed anytime (and thus break your code).

If you can describe a use case where giving access to this function to the user is helpful then I will think about exporting the generic, and pay attention not to break compatibility with updates. But doing so adds complexity and maintenance work to the project, so I would prefer to avoid doing it if there is not clear need for it.

**Comment by MattWiener** [comment]
Sorry - I figured out my problem.  Instead of reloading the package from github, I tried to use fixInNamespace to just put in the one line in the recent fix to eval_matrix.   That ended up changing the function environment, which caused a whole bunch of problems.   Just reinstalling the package from github took care of it.   Sorry for the disturbance.

**Comment by pierucci** [comment]
No problem!
